### ISSUE TITLE
Incompatible with React v15.5.4

### ISSUE THREAD

**Issue by sorenjuul** [sebinsua/react-redux-simple-modal#1]
Do you plan to update this module to support the newest version of React?

**Comment by sebinsua** [comment]
Hi. I'm on holiday this week but I'll take a look at this when I get home.

What's not supported?

**Comment by sebinsua** [comment]
I updated the `devDependencies` to use new versions of everything, and I couldn't see anything I needed to fix. I tested with the logic within `example/` and the unit tests which were already there. It still seems to work. Feel free to clone the repo and see for yourself by opening the example folder and running `npm start` inside it. Is there anything else that's broken which I've not noticed?

I do notice there is a warning about `prop-types` but I can't see any usage of `propTypes` within my own code. This is a minor issue anyway which is probably just a problem caused by the build. 

More likely there is a problem with how the package is being used within your own application.

**Comment by vybu** [comment]
I think it's all good now. Can't see any warning now.
